### ISSUE TITLE
Base Maven project structure for extensions repository.

### ISSUE THREAD

**Issue by tomaszmichalak** [Knotx/knotx-extensions#1]
Knot.x Core modules:
1. Roots (Common, Server, Splitter, Repositories)
2. Knots (API, Action Knot, Service Knot, Handlebars Knot)
3. Adapters (API, Http Service Adapter)

In Knot.x Extensions Repository we propose different modules structure approach. This repository contains modules / components which are project agnostic but address specific problems and solve them. So it can be understand as feature repository - natural approach in this case is module by feature structure.

```
/knotx-ext-authentication/
/knotx-ext-action/
/knotx-ext-cache/
pom.xml
```
At this point it is important to be aware of the fact that different features will be compatible with different Knot/Adapter APIs.

**Comment by Skejven** [comment]
This is outdated issue.
